import "./globals.css";
import Navbar from "./../components/main/navbar/Navbar";

import localFont from "next/font/local";

const vazirFont = localFont({
  src: "../public/font/Vazirmatn-VariableFont_wght.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className}>
        <main className="container">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
